version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kmv-laravel-app
    container_name: kmv-laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      APP_URL: http://localhost:8000
    networks:
      - kmv-network
    ports:
      - '8000:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      timeout: 3s
      retries: 5

  react:
    image: node:18-alpine
    container_name: kmv-react
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '5173:5173'
    networks:
      - kmv-network
    command: npm run dev
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

networks:
  kmv-network:
    driver: bridge

